# 核心任务

- name: open-falcon
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}
    - {role: centos-mysql, tags: "centos-mysql"}
    - { role: nginx, tags: "nginx"}    
    - { role: redis, tags: "redis"} 
    - { role: open-falcon, tags: "open-falcon"}
    # - { role: docker, tags: "docker"}
    # - { role: docker_phpmyadmin, tags: "docker_phpmyadmin"}





    


                                                                                                    